version: "3"
services:
  postgres:
    image: "postgres:9"
    networks:
      - web
    env_file:
      - env/dev.env

  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    labels:
      app: wac-backend
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - web
    depends_on:
      - postgres
    env_file:
      - env/dev.env


networks:
  web:
